apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolov8-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolov8-webapp
  template:
    metadata:
      labels:
        app: yolov8-webapp
    spec:
      containers:
        - name: yolov8-webapp
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources: {{- toYaml .Values.resources | nindent 12 }}
