apiVersion: v1
kind: Service
metadata:
  name: yolov8-webapp
spec:
  selector:
    app: yolov8-webapp
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
