image:
  repository: ghcr.io/wangsouza/yolov8-webapp
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

# Optional: add imagePullSecrets when using private registries
imagePullSecrets:
  - name: ghcr-creds
